version: "3"

services: 
    db:
        image: postgres:9.5
        container_name: db
        volumes:
            - db-data:/var/lib/postgresql/data        
    
    result:
        build: .
        environment: 
            - CON_STRING=postgres://postgres@db/postgres
        depends_on: 
            - db

volumes: 
    db-data: